# Generated by Django 4.2.3 on 2023-08-10 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_alter_item_options_remove_item_listing_stauts_and_more"),
        ("transaction_messages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="item_id",
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to="items.item"),
            preserve_default=False,
        ),
    ]
