# Generated by Django 4.2.3 on 2023-08-17 05:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "ユーザー"},
        ),
        migrations.RemoveField(
            model_name="user",
            name="student_number",
        ),
    ]
