# Generated by Django 4.2.3 on 2023-08-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_options_remove_user_student_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="アカウント有効フラグ"),
        ),
    ]
