version: '3.8'
services:
  react-app:
    container_name: react_app
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend.prod
    ports:
      - "8080:80"
    restart: unless-stopped
