# Generated by Django 4.2.3 on 2023-11-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_important",
            field=models.BooleanField(default=False),
        ),
    ]
