FROM python:3.11-slim-bullseye

RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
RUN pip install --upgrade pip

WORKDIR /app
COPY docker-requirements.txt ./
RUN pip install -r docker-requirements.txt

COPY . /app/
