# Generated by Django 4.2.3 on 2023-07-08 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import items.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("campuses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "listing_stauts",
                    models.CharField(
                        choices=[
                            ("unpurchased", "未購入"),
                            ("purchased", "購入済み"),
                            ("completed", "取引完了"),
                            ("canceled", "キャンセル済み"),
                        ],
                        default="unpurchased",
                        max_length=30,
                    ),
                ),
                ("price", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=255)),
                (
                    "condition",
                    models.CharField(
                        choices=[("new", "未使用"), ("fine", "目立った傷や汚れなし"), ("used", "使用感あり"), ("damaged", "破損あり")],
                        max_length=30,
                    ),
                ),
                (
                    "writing_state",
                    models.CharField(choices=[("none", "全くない"), ("little", "少しある"), ("lot", "かなりある")], max_length=30),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="buys", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "receivable_campus",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="campuses.campus"),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sells", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "出品",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("photo", models.ImageField(upload_to=items.models.get_item_image_path)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("parent_item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="items.item")),
            ],
        ),
    ]
