# Generated by Django 4.2.3 on 2023-08-31 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import items.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("campuses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "listing_status",
                    models.CharField(
                        choices=[
                            ("unpurchased", "未購入"),
                            ("purchased", "購入済み"),
                            ("completed", "取引完了"),
                            ("canceled", "キャンセル済み"),
                        ],
                        default="unpurchased",
                        max_length=11,
                    ),
                ),
                ("price", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=255)),
                (
                    "condition",
                    models.CharField(
                        choices=[("brandNew", "未使用"), ("fine", "目立った傷や汚れなし"), ("used", "使用感あり"), ("damaged", "破損あり")],
                        max_length=8,
                    ),
                ),
                (
                    "writing_state",
                    models.CharField(choices=[("none", "全くない"), ("little", "少しある"), ("lot", "かなりある")], max_length=6),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buy_item",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receivable_campus",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="campuses.campus"),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sell_item",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="liked_by", to="items.item"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("photo_path", models.ImageField(upload_to=items.models.get_item_image_path)),
                ("order", models.PositiveSmallIntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="images", to="items.item"
                    ),
                ),
            ],
        ),
    ]
