# Generated by Django 4.2.3 on 2023-07-13 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("campuses", "0001_initial"),
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={},
        ),
        migrations.RemoveField(
            model_name="item",
            name="listing_stauts",
        ),
        migrations.AddField(
            model_name="item",
            name="listing_status",
            field=models.CharField(
                choices=[
                    ("unpurchased", "未購入"),
                    ("purchased", "購入済み"),
                    ("completed", "取引完了"),
                    ("canceled", "キャンセル済み"),
                ],
                default="unpurchased",
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buy_item",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="condition",
            field=models.CharField(
                choices=[("new", "未使用"), ("fine", "目立った傷や汚れなし"), ("used", "使用感あり"), ("damaged", "破損あり")], max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="item",
            name="receivable_campus",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="campuses.campus"),
        ),
        migrations.AlterField(
            model_name="item",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="sell_item", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="writing_state",
            field=models.CharField(choices=[("none", "全くない"), ("little", "少しある"), ("lot", "かなりある")], max_length=6),
        ),
    ]
