# Generated by Django 4.2.3 on 2023-08-17 08:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_alter_item_options_remove_item_listing_stauts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
