# Generated by Django 4.2.3 on 2023-08-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0005_rename_photo_image_photo_url_image_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="order",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
