# Generated by Django 4.2.3 on 2023-08-21 00:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0006_alter_image_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="photo_url",
            new_name="photo_path",
        ),
    ]
