# Generated by Django 4.2.3 on 2023-08-21 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0007_rename_photo_url_image_photo_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="parent_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="images", to="items.item"
            ),
        ),
    ]
