# Generated by Django 4.2.3 on 2023-08-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0010_alter_item_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="condition",
            field=models.CharField(
                choices=[("brandNew", "未使用"), ("fine", "目立った傷や汚れなし"), ("used", "使用感あり"), ("damaged", "破損あり")],
                max_length=8,
            ),
        ),
    ]
