name: Django Run Tests

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    # pipenvのインストール
    - name: Install pipenv
      run: |
        pip install pipenv
    # 依存関係のインストール
    - name: Install dependencies
      run: |
        pipenv install --dev
      working-directory: ./server/app
    - name: Run Tests
      run: |
        pipenv run python manage.py test
      working-directory: ./server/app
      env:
        DJANGO_SETTINGS_MODULE: config.settings.dev
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: True
        LANGUAGE_CODE: ja
        TIME_ZONE: Asia/Tokyo
        CLIENT_URL: http://localhost:3000
        
        
        
